version: '3.9'

services:
  elixir:
    build: 
      context: .
      dockerfile: Dockerfile_dev
    container_name: wms_tasks
    user: "${UID}:${GID}"
    ports:
      - "4000:4000"
    environment:
      MIX_ENV: dev
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/wms_task
    volumes:
      - ./:/app
    depends_on:
      - postgres
  postgres:
    image: postgres:11-alpine
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: "wms_task_dev"

volumes:
  postgres-data:
    driver: local
    