name: Elixir Build and Test
env:
  MIX_ENV: test

on: [push]

jobs:
  build:
    timeout-minutes: 7
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:12.3
        ports: ['5432:5432']
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: wms_task_test
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 24.0
          elixir-version: 1.12

      - name: Get Deps Cache
        uses: actions/cache@v2
        id: deps
        with:
          path: deps/
          key: ${{hashFiles('mix.lock')}}-deps

      - name: Get Build Cache
        uses: actions/cache@v2
        with:
          path: _build/
          key: ${{runner.os}}-${{hashFiles('mix.lock')}}-build

      - name: Get deps
        if: steps.deps.outputs.cache-hit != 'true'
        run: | 
          mix deps.get

      - name: Install Dependencies
        run: |
          mix compile --warnings-as-errors

      - name: Migrate Base
        run: |
          mix ecto.create
          mix ecto.migrate

      - name: Check format
        run: |
          mix format --check-formatted

      - name: Check CREDO
        run: |
          mix credo --strict

      - name: Run Tests
        run: |
          mix test
